languageCode = "en-us"
title = "Rohan Hasabe"
theme = "hugo-bearblog"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 10

# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[author]
  name = "Rohan Hasabe"

[params]
  # Date format for blog posts
  dateFormat = "Jan 2, 2006"
  # Metadata mostly used in document's head
  # 
  description = "Rohan Hasabe's personal website"
  keywords = "portfolio, blog, programming"

  # Social icons
  [[params.social]]
      name = "GitHub"
      icon = "lab la-github-square la-2x"
      url = "https://github.com/Hasaber8"
  [[params.social]]
      name = "Linkedin"
      icon = "lab la-linkedin-in la-2x"
      url = "https://www.linkedin.com/in/hasaber8"
  [[params.social]]
      name = "Twitter"
      icon = "lab la-twitter la-2x"
      url = "https://twitter.com/hasaber8"

[languages]
  [languages.en]
      subtitle  = ""
      weight    = 1

[[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 1
